GET http://localhost:3000/

###
GET http://localhost:3000/5e0969f9941e2d56a2120bed

###
POST http://localhost:3000/
Content-Type: application/json

{
    "name": "Nike Air",
    "type": "shoes"
}

###
DELETE http://localhost:3000/5e099108a87fd7c666a56ba4

###
PATCH http://localhost:3000/5e0a444ff240783ea62c0273
Content-Type: application/json

{
    "name": "Adidas Stripes"
}